name: Build

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: microsoft/setup-msbuild@v1

      - name: Build
        run: msbuild PacketTracerRecovery.sln /p:Configuration=Release

      - name: Upload build files
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: |
            PacketTracerInjector/**/Release/*
            PacketTracerDll/**/Release/*
            PacketTracerInjector/**/Debug/*
            PacketTracerDll/**/Debug/*
