name: Build C++ Project

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build Solution
        run: msbuild PacketTracerRecovery.sln /p:Configuration=Release
